### ISSUE TITLE
Compare Players

### ISSUE THREAD

**Issue by behlulkeremsisman** [BehlulKeremSisman/basketball-gm#3]
This system is going to show which player is better or worse than the other in all features. Manager can compare players while he could not decide about trade those two player. He can compare and  realise which player is effective for his requests. There will be a lot of physical, mental, ability features to compare. This system is useful for trading players, signing a free agent player or deciding for starting line-up.

**Comment by cagdasgerede** [comment]
Kriterlere uygun değil.

minimum 700 karakter olması gerekiyor.

**Comment by cagdasgerede** [comment]
ok

**Comment by BehlulKeremSisman** [comment]
Hocam 2 farklı issue belirledim. Training ve compare.

**Comment by BehlulKeremSisman** [comment]
Yalnızca tek bir issue yapanlar icin 700 karakter kısıtlaması var diye
biliyorum. 2. İssue'mun 700 karakter olmaması sorun teşkil ediyor muydu ?

**Comment by behlulkeremsisman** [comment]
Hocam sizinle konustugumuz gibi Issue #1 (Training) uzerinde focuslanmam icin bu issueyu kapatabilirsin demistiniz.
